export const CART_ACTION_TYPES = {
  SET_ITEM_TO_CART: "SET_ITEM_TO_CART",
  SUBTRACT_ITEM_FROM_CART: "SUBTRACT_ITEM_FROM_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  OPEN_CART: "OPEN_CART",
  SET_CART_TOTAL: "SET_CART_TOTAL",
};
