export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_MAP_START: "FETCH_CATEGORIES_MAP_START",
  FETCH_CATEGORIES_MAP_SUCCESS: "FETCH_CATEGORIES_MAP_SUCCESS",
  FETCH_CATEGORIES_MAP_FAILED: "FETCH_CATEGORIES_MAP_FAILED",
};
